[platformio]
default_envs = blink, serial_status, motor_reg
src_dir = src

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino

[env:blink]
build_src_filter =
    -<*>
    +<blink/>

[env:serial_status]
monitor_speed = 115200
build_src_filter =
    -<*>
    +<serial_status/>

[env:motor_reg]
monitor_speed = 115200
lib_deps =
    arduino-libraries/Servo @ ^1.2.2
build_src_filter =
    -<*>
    +<motor_reg/>
