[platformio]
default_envs = blink, serial_status
src_dir = src

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino

[env:blink]
build_src_filter =
    -<*>
    +<blink/>

[env:serial_status]
monitor_speed = 115200
build_src_filter =
    -<*>
    +<serial_status/>
